// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_D7r4NLwz8hxaJfPsksB1YvoSL__m6II',
    appId: '1:751283654969:web:574f122f7b12d0acfb98e8',
    messagingSenderId: '751283654969',
    projectId: 'baberapp-cab90',
    authDomain: 'baberapp-cab90.firebaseapp.com',
    storageBucket: 'baberapp-cab90.appspot.com',
    measurementId: 'G-SW25TQMHYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-xBsdC86aPtf_hpNimZ-ZcLBoVDcsBc',
    appId: '1:751283654969:android:c730242839621dedfb98e8',
    messagingSenderId: '751283654969',
    projectId: 'baberapp-cab90',
    storageBucket: 'baberapp-cab90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb9TiEeHqxJLWDpMGzvSYhLnYORFZgsXs',
    appId: '1:751283654969:ios:fed8efbfca44dbeafb98e8',
    messagingSenderId: '751283654969',
    projectId: 'baberapp-cab90',
    storageBucket: 'baberapp-cab90.appspot.com',
    iosClientId: '751283654969-udi0fgeq28ef1ujsr2ru9bkm6pqfs0bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.baber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb9TiEeHqxJLWDpMGzvSYhLnYORFZgsXs',
    appId: '1:751283654969:ios:fed8efbfca44dbeafb98e8',
    messagingSenderId: '751283654969',
    projectId: 'baberapp-cab90',
    storageBucket: 'baberapp-cab90.appspot.com',
    iosClientId: '751283654969-udi0fgeq28ef1ujsr2ru9bkm6pqfs0bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.baber',
  );
}
