// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXc3uMkMjKqeTO_1-pqYNN55vt8FKGup8',
    appId: '1:33242133420:web:f40a369295aacde0118009',
    messagingSenderId: '33242133420',
    projectId: 'baberapp-e0472',
    authDomain: 'baberapp-e0472.firebaseapp.com',
    storageBucket: 'baberapp-e0472.appspot.com',
    measurementId: 'G-1N0SYGDKJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7S0ztNKB24qKcW1cd-QS92bCQRnQywFw',
    appId: '1:33242133420:android:696815cccbc8c336118009',
    messagingSenderId: '33242133420',
    projectId: 'baberapp-e0472',
    storageBucket: 'baberapp-e0472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqgVftnVBJq6WxXI75pGC696TsZ7nrn8',
    appId: '1:33242133420:ios:89234f97f7593992118009',
    messagingSenderId: '33242133420',
    projectId: 'baberapp-e0472',
    storageBucket: 'baberapp-e0472.appspot.com',
    iosClientId: '33242133420-acslj6f8cmcmeqc5a6dd5qrqvrkd5r70.apps.googleusercontent.com',
    iosBundleId: 'com.example.baber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqgVftnVBJq6WxXI75pGC696TsZ7nrn8',
    appId: '1:33242133420:ios:89234f97f7593992118009',
    messagingSenderId: '33242133420',
    projectId: 'baberapp-e0472',
    storageBucket: 'baberapp-e0472.appspot.com',
    iosClientId: '33242133420-acslj6f8cmcmeqc5a6dd5qrqvrkd5r70.apps.googleusercontent.com',
    iosBundleId: 'com.example.baber',
  );
}
